[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "ConTrack"
author = "EmptyBlueBox"
maintainer = "EmptyBlueBox"
description = "Minimal Isaac Lab mimic learning tasks for xArm and XHand."
repository = "https://github.com/EmptyBlueBox/ConTrack.git"
keywords = ["isaaclab", "mimic", "rsl_rl", "contrack"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
[[python.module]]
name = "ConTrack"
